\copy Calendar from C:/Users/rsaen/Documents/SQL_CS327E/2017-03-07/calendar.csv (format csv, header true)
\copy Listings from C:/Users/rsaen/Documents/SQL_CS327E/2017-03-07/listings.csv (format csv, header true)
\copy Neighbourhoods from C:/Users/rsaen/Documents/SQL_CS327E/2017-03-07/neighbourhoods.csv (format csv, header true)
\copy Reviews from C:/Users/rsaen/Documents/SQL_CS327E/2017-03-07/reviews.csv (format csv, header true)
\copy Summary_Listings from C:/Users/rsaen/Documents/SQL_CS327E/2017-03-07/summary_listings.csv (format csv, header true)
\copy Summary_Reviews from C:/Users/rsaen/Documents/SQL_CS327E/2017-03-07/summary_reviews.csv (format csv, header true)